https://www.toptechskills.com/ansible-tutorials-courses/how-to-fix-usr-bin-python-not-found-error-tutorial/

╷
│ Error: local-exec provisioner error
│ 
│   with aws_instance.bastion,
│   on main.tf line 134, in resource "aws_instance" "bastion":
│  134:   provisioner "local-exec" {
│ 
│ Error running command 'ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu -i '44.192.40.235,' --private-key ~/.ssh/instance_ssh.pem -e 'pub_key=~/.ssh/instance_ssh.pub.pub'
│ /home/ubuntu/environment/learnTerraformAWSInstance/ansible/site.yml': exit status 2. Output: 
│ PLAY [apache-install] **********************************************************
│ 
│ TASK [Gathering Facts] *********************************************************
│ ok: [44.192.40.235]
│ 
│ TASK [Add the user 'gremlin' and add it to 'sudo'] *****************************
│ changed: [44.192.40.235]
│ 
│ TASK [Add SSH key to 'gremlin'] ************************************************
│  [WARNING]: Unable to find 'pvt_key' in expected paths (use -vvvvv to see
│ paths)
│ fatal: [44.192.40.235]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: pvt_key"}
│       to retry, use: --limit @/home/ubuntu/environment/learnTerraformAWSInstance/ansible/site.retry
│ 
│ PLAY RECAP *********************************************************************
│ 44.192.40.235              : ok=2    changed=1    unreachable=0    failed=1   